## Numpy array  and basics
learn about numpy

In [1]:
import  numpy as np 

## createing array  from list

In [2]:
arr_1d=np.array([10, 20, 30, 40, 50])
arr_2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_3d=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("1D Array:")
print(arr_1d) 
print("2D Array:")
print(arr_2d)
print("3D Array:")
print(arr_3d)

1D Array:
[10 20 30 40 50]
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Vector , Matrix , Tensor

In [ ]:
vertor=np.array([1,2,3,4,5])
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
tensor=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Vector:")  
print(vertor)
print("Matrix:")
print(matrix)
print("Tensor:")
print(tensor)
